# Ejemplo de configuración para cloudflared
# Este archivo se genera automáticamente con el script setup-cloudflare-tunnel.sh

# Configuración del túnel
tunnel = "tu-tunnel-id"
credentials-file = "/etc/cloudflared/credentials.json"

# Configuración de ingress (enrutamiento)
[ingress]
  # Ruta por defecto
  [[ingress.rules]]
    hostname = "barkandmeow.tudominio.com"
    service = "http://localhost:3000"
  
  # Regla de captura para cualquier otra solicitud
  [[ingress.rules]]
    service = "http_status:404"

# Configuración de logs
loglevel = "info"

