version: '3'

services:
  app:
    image: topgambajrjdeveloper/barkandmeow
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_APP_URL=https://barkandmeow-latest.onrender.com
      - NEXTAUTH_URL=https://barkandmeow-latest.onrender.com
      - AUTH_URL=https://barkandmeow-latest.onrender.com
      - SITE_URL=https://barkandmeow-latest.onrender.com

