version: '3'

services:
  app:
    image: topgambajrjdeveloper/barkandmeow
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_APP_URL=https://barkandmeow.tudominio.com
      - NEXTAUTH_URL=https://barkandmeow.tudominio.com
      - AUTH_URL=https://barkandmeow.tudominio.com
      - SITE_URL=https://barkandmeow.tudominio.com

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - app

