version: '3'

services:
  app:
    image: topgambajrjdeveloper/barkandmeow
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_APP_URL=https://barkandmeow.app
      - NEXTAUTH_URL=https://barkandmeow.app
      - AUTH_URL=https://barkandmeow.app
      - SITE_URL=https://barkandmeow.app

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token 709ce01f-b5f1-4122-90b3-35937789cf94
    depends_on:
      - app