import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/providers/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import { SessionProvider } from "next-auth/react";
import { UserProvider } from "@/contexts/UserContext";
import { Header } from "@/components/(root)/ui/header";
import { MobileNavigation } from "@/components/(root)/ui/MobileNavigation";
import Footer from "@/components/(root)/ui/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       <SessionProvider>
          <UserProvider>
            <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
              <div className="flex min-h-screen flex-col">
                <Header />
                <main className="flex-1">
                  <div className="container max-w-custom mx-auto px-4 py-8">{children}</div>
                </main>
                <MobileNavigation />
                <Footer />
              </div>
            </ThemeProvider>
          </UserProvider>
        </SessionProvider>
        <Toaster />
      </body>
    </html>
  );
}
